### ISSUE TITLE
Lesson 1 link is broken

### ISSUE THREAD

**Issue by jondaiello** [philschanely/course-web1#2]
The lesson 1 link is not functional yet.
http://web1.philschanely.com/lessons/01-intro-to-html.html

**Comment by philschanely** [comment]
This silly link has given me more trouble! Working on the fix now.

**Comment by philschanely** [comment]
Building and deploying now.

**Comment by jondaiello** [comment]
👍  Let me know when you're ready for me to review.

**Comment by philschanely** [comment]
OK build is finished and deployed; I have checked it but please verify it works for you now as well.

**Comment by jondaiello** [comment]
Approved! Nice work. 🏆

**Comment by philschanely** [comment]
👍
